"""
Email Service - Week 6
Sends session outputs via email using Resend
"""
import resend
import os

resend.api_key = os.getenv('RESEND_API_KEY')


class EmailService:
    async def send_session_output(
        self,
        to_email: str,
        soap_note: str,
        core_elms: str,
        session_number: int
    ) -> bool:
        """
        Email session outputs to user

        Args:
            to_email: Recipient email
            soap_note: Generated SOAP note
            core_elms: Generated CORE ELMS output
            session_number: Session number

        Returns:
            True if sent successfully
        """
        # TODO: Week 6 - Implement email sending
        try:
            params = {
                "from": "NeuroBridge <noreply@neurobridge.ai>",
                "to": [to_email],
                "subject": f"Session #{session_number} - Clinical Documentation",
                "html": self._format_email_html(soap_note, core_elms, session_number)
            }

            # Uncomment when ready:
            # email = resend.Emails.send(params)
            # return True

            return True
        except Exception as e:
            print(f"Email error: {e}")
            return False

    def _format_email_html(self, soap_note: str, core_elms: str, session_number: int) -> str:
        """Format email HTML"""
        return f"""
        <html>
        <body>
            <h2>Session #{session_number} Documentation</h2>

            <h3>SOAP Note</h3>
            <pre>{soap_note}</pre>

            <h3>CORE ELMS</h3>
            <pre>{core_elms}</pre>

            <p><small>Generated by NeuroBridge AI Clinical Assistant</small></p>
        </body>
        </html>
        """
