import {
  Controller,
  Post,
  Get,
  Body,
  Param,
  UseGuards,
  HttpCode,
  HttpStatus,
  Request,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiBearerAuth } from '@nestjs/swagger';
import { RiskService } from './risk.service';
import {
  RiskAlertsResponseDto,
  ResolveAlertDto,
  ScanPatientDto,
  RiskScoreDto,
} from './dto';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { UserRole } from '@prisma/client';

/**
 * Patch 04: Risk Controller
 * Risk alerts fusion (medication changes + mood patterns)
 */
@ApiTags('Risk Alerts')
@Controller('risk')
@UseGuards(JwtAuthGuard, RolesGuard)
@ApiBearerAuth()
export class RiskController {
  constructor(private readonly riskService: RiskService) {}

  /**
   * GET /risk/alerts/:patientId
   * Provider: Get active risk alerts for patient
   */
  @Get('alerts/:patientId')
  @Roles(UserRole.PROVIDER, UserRole.MENTOR, UserRole.ADMIN)
  @ApiOperation({
    summary: 'Get patient risk alerts',
    description: 'Returns active and resolved risk alerts. Alerts are generated by fusing medication changes with mood patterns.',
  })
  @ApiResponse({
    status: 200,
    description: 'Alerts retrieved',
    type: RiskAlertsResponseDto,
  })
  async getPatientAlerts(
    @Param('patientId') patientId: string,
  ): Promise<RiskAlertsResponseDto> {
    return this.riskService.getPatientAlerts(patientId);
  }

  /**
   * POST /risk/resolve
   * Provider: Resolve a risk alert
   */
  @Post('resolve')
  @Roles(UserRole.PROVIDER, UserRole.MENTOR, UserRole.ADMIN)
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Resolve risk alert',
    description: 'Mark alert as resolved with action taken. Records provider ID and notes.',
  })
  @ApiResponse({
    status: 200,
    description: 'Alert resolved',
  })
  @ApiResponse({
    status: 404,
    description: 'Alert not found',
  })
  async resolveAlert(
    @Body() dto: ResolveAlertDto,
    @Request() req: any,
  ): Promise<{ success: boolean }> {
    const providerId = req.user?.providerId || req.user?.id;
    return this.riskService.resolveAlert(dto, providerId);
  }

  /**
   * POST /risk/scan
   * Provider/Admin: Manually trigger risk scan
   */
  @Post('scan')
  @Roles(UserRole.PROVIDER, UserRole.ADMIN)
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Scan patient for risks',
    description: 'Manually trigger risk analysis. Correlates recent medication changes with mood patterns. Normally runs automatically on events.',
  })
  @ApiResponse({
    status: 200,
    description: 'Risk scan completed',
    type: RiskScoreDto,
  })
  @ApiResponse({
    status: 404,
    description: 'Patient not found',
  })
  async scanPatient(@Body() dto: ScanPatientDto): Promise<RiskScoreDto> {
    return this.riskService.scanPatient(dto);
  }
}
